return {
  lua_ls = require("plugins.lsp.server.lua_ls"),
  elixirls = { cmd = { "elixir-ls" } },
  html = {},
  cssls = {},
  jsonls = require("plugins.lsp.server.json_ls"),
  tailwindcss = require("plugins.lsp.server.tailwind"),
  emmet_language_server = {},
  astro = {},
  pyright = {},
  ruby_ls = {},
  zls = {},
  hls = require("plugins.lsp.server.hls"),
  ocamllsp = {},
  svelte = {},
  gleam = {},
}
